/**
 * General constants
 *
 * @package buyers-experience
 */
type WithPrefix<T extends string> = `${T}${string}`;
type ADVANCED_SEARCH = WithPrefix<'ADVANCED_SEARCH'>;

export const LICENSE_SERVICE: ADVANCED_SEARCH = 'ADVANCED_SEARCH-3068620';
export const LICENSE_ADMIN_UI: ADVANCED_SEARCH = 'ADVANCED_SEARCH-2404952';
export const LICENSE_TRAP_PRIMARY: ADVANCED_SEARCH = 'ADVANCED_SEARCH-4614996';
export const LICENSE_TRAP_SECONDARY: ADVANCED_SEARCH = 'ADVANCED_SEARCH-1770225';

export const ES_MULTILINGUAL_INDEX: string = 'ES_MULTILINGUAL_INDEX';
