/**
 * @package system-settings
 */
export default {
    customer: [{
        property: 'email',
        label: 'sw-customer.list.columnEmail',
        routerLink: 'sw.customer.detail',
        primary: true,
        width: '200px',
    },
    {
        property: 'firstName',
        dataIndex: 'firstName',
        label: 'First name',
        routerLink: 'sw.customer.detail',
        width: '150px',
    },
    {
        property: 'lastName',
        dataIndex: 'lastName',
        label: 'Last name',
        routerLink: 'sw.customer.detail',
        width: '150px',
    },
    {
        property: 'customerNumber',
        dataIndex: 'customerNumber',
        label: 'sw-customer.list.columnCustomerNumber',
        align: 'right',
    },
    {
        property: 'affiliateCode',
        label: 'sw-customer.list.columnAffiliateCode',
    },
    {
        property: 'campaignCode',
        label: 'sw-customer.list.columnCampaignCode',
    }],
    product: [{
        property: 'name',
        label: 'sw-product.list.columnName',
        routerLink: 'sw.product.detail',
        inlineEdit: 'string',
        allowResize: true,
        primary: true,
    },
    {
        property: 'productNumber',
        naturalSorting: true,
        label: 'sw-product.list.columnProductNumber',
        align: 'right',
        allowResize: true,
    },
    {
        property: 'stock',
        label: 'sw-product.list.columnInStock',
        inlineEdit: 'number',
        allowResize: true,
        align: 'right',
    },
    {
        property: 'availableStock',
        label: 'sw-product.list.columnAvailableStock',
        allowResize: true,
        align: 'right',
    },
    {
        property: 'createdAt',
        label: 'sw-product.list.columnCreatedAt',
        allowResize: true,
        visible: false,
    },
    {
        property: 'updatedAt',
        label: 'sw-product.list.columnUpdatedAt',
        allowResize: true,
        visible: false,
    }],
    order: [{
        property: 'orderNumber',
        label: 'sw-order.list.columnOrderNumber',
        routerLink: 'sw.order.detail',
        allowResize: true,
        primary: true,
    },
    {
        property: 'billingAddressId',
        dataIndex: 'billingAddress.street',
        label: 'sw-order.list.columnBillingAddress',
        allowResize: true,
    },
    {
        property: 'amountTotal',
        label: 'sw-order.list.columnAmount',
        align: 'right',
        allowResize: true,
    },
    {
        property: 'orderDateTime',
        label: 'sw-order.list.orderDate',
        allowResize: true,
    },
    {
        property: 'affiliateCode',
        inlineEdit: 'string',
        label: 'sw-order.list.columnAffiliateCode',
        allowResize: true,
        visible: false,
    },
    {
        property: 'campaignCode',
        inlineEdit: 'string',
        label: 'sw-order.list.columnCampaignCode',
        allowResize: true,
        visible: false,
    }],
    product_price: [{
        property: 'productId',
        dataIndex: 'productId',
        label: 'product_id',
        width: '250px',
        primary: true,
    },
    {
        property: 'ruleId',
        dataIndex: 'ruleId',
        label: 'rule_id',
    },
    {
        property: 'priceNet',
        dataIndex: 'priceNet',
        label: 'Net price',
    },
    {
        property: 'priceGross',
        dataIndex: 'priceGross',
        label: 'Gross price',
    },
    {
        property: 'quantityStart',
        dataIndex: 'quantityStart',
        label: 'Quantity Start',
    },
    {
        property: 'quantityEnd',
        dataIndex: 'quantityEnd',
        label: 'Quantity End',
    }],
    category: [{
        property: 'name',
        dataIndex: 'name',
        label: 'Name',
        width: '250px',
        primary: true,
    },
    {
        property: 'description',
        dataIndex: 'description',
        label: 'Description',
    },
    {
        property: 'type',
        dataIndex: 'type',
        label: 'Type',
    }],
    media: [{
        property: 'fileName',
        dataIndex: 'fileName',
        label: 'File name',
        width: '250px',
        primary: true,
    },
    {
        property: 'fileSize',
        dataIndex: 'fileSize',
        label: 'Size (in Byte)',
    },
    {
        property: 'fileExtension',
        dataIndex: 'fileExtension',
        label: 'File Extension',
    },
    {
        property: 'uploadedAt',
        dataIndex: 'uploadedAt',
        label: 'Uploaded at',
    }],
    newsletter_recipient: [{
        property: 'email',
        dataIndex: 'email',
        label: 'Email',
        routerLink: 'sw.newsletter.recipient.detail',
        width: '250px',
        primary: true,
    },
    {
        property: 'title',
        dataIndex: 'title',
        label: 'Title',
        align: 'right',
    },
    {
        property: 'firstName',
        dataIndex: 'firstName',
        label: 'First name',
        align: 'right',
    },
    {
        property: 'lastName',
        dataIndex: 'lastName',
        label: 'Last name',
        align: 'right',
    }],
    promotion_individual_code: [{
        property: 'code',
        dataIndex: 'code',
        label: 'Code',
        width: '250px',
        primary: true,
    }],
    promotion_discount: [{
        property: 'promotionId',
        dataIndex: 'promotionId',
        label: 'promotion_id',
        width: '250px',
        primary: true,
    }, {
        property: 'scope',
        dataIndex: 'scope',
        label: 'Scope',
    }, {
        property: 'type',
        dataIndex: 'type',
        label: 'Type',
    }, {
        property: 'value',
        dataIndex: 'value',
        label: 'Value',
    }],
    property_group_option: [{
        property: 'name',
        dataIndex: 'name',
        label: 'Option name',
        width: '250px',
        primary: true,
    }],
    product_cross_selling: [{
        property: 'name',
        dataIndex: 'name',
        width: '250px',
        primary: true,
    }],
};
