= Publisher State Transitions v2

Contains extension of v2 state diagrams


### v2 Demo Workflow

[plantuml, publisher-demo-workflow, svg]
....

Edit: Role: Editor
Edit: Description:
Review: Role: Reviewer
Review: Description: A peer review can decide whether the change is fit for the shop
ReadyForLive: Role: Publisher
ReadyForLive: Description: The review did succeed, and the changes can be pushed live a final verdict can be made.

[*] -down-> Edit : draft
Edit -down-> Review : submit
Review -down-> ReadyForLive : success
Review -down-> Edit : needs work
ReadyForLive -down-> [*] : publish


Edit  -down-> [*] : abort
Review  -down-> [*] : discard
ReadyForLive -down-> [*] : discard
....

### Entity States

[plantuml, publisher-entity-states-v2, svg]
....

state live : live version
state draft : a non live version

[*] --> live : create
live -down-> draft : draft
live --> live : save-changes
draft -up-> live : merge

draft --> draft : save-changes
draft --> draft : duplicate
draft --> draft : update-from-live
draft --> draft : transition

live -left-> [*] : delete
draft --> [*] : discard
....

##### Update

* *transition* -> transition into user defined state