= Publisher State Transitions v2

### Page-States transition example

Visualization of the draft/update/discard process

##### Page States

* livep1 => Page 1, Live
* lifep2 => Page 2, Live
* versions => collection of drafts
* v[1...4] => a specific version

##### Actions

* draft => creating a draft from parent page
* release => setting the content of draft x live
* discard => removing the version
* new => creating a new live version from draft
* update => reset draft to current live version


[plantuml, publisher-state-transition-example, svg]
....
hide empty description

state livep1 {
    [*] -right-> v1 : create
    v1 -[hidden]right-> v2 : update
    v2 -[hidden]right-> v3 : update
    v3 -[hidden]right-> v4 : update
    v4 -right-> v5 : update
    v5 -right-> [*] : delete
}

state livep2 {
    state v1p2
    v1p2 -right-> [*] : delete

}

state versions  {
    v1 --> v2.draft : draft
    v2.draft -up-> v2 : release
    v2 --> v3.draft : draft
    v3.draft -up-> v3 : release

    v2 --> v3.draft2 : draft
    v3 --> v3.draft2 : update
    v3.draft2 -up-> v4 : release

    v4 --> v4.draft : draft
    v4.draft --> [*] : discard

    v4 --> v4.draft2 : draft
    v4.draft2 -down-> v1p2 : new
}

livep1 -[hidden]down-> versions
versions -[hidden]left-> livep2
....

### Entity States

[plantuml, publisher-entity-states, svg]
....

state live : live version
state draft : a non live version

[*] --> live : create
live -down-> draft : draft
live --> live : save-changes
draft -up-> live : merge
draft -up-> live : release as new

draft --> draft : save-changes
draft --> draft : duplicate
draft --> draft : update-from-live

live -left-> [*] : delete
draft --> [*] : discard
....

##### States

* *live* -> an existing record, can be accessible from the storefront. Possibly connected to categories
* *draft* -> inaccessible from the storefront, possibly contains changes.

##### Transitions

* *create* -> create live version of page
* *delete* -> remove a live version, implicitly removes all drafts
* *draft* -> branch off current live version into draft
* *save-changes* -> merge changes into existing page or draft (= current subject)
* *discard* -> remove draft and discard all changes made
* *duplicate* -> branch off current draft into another draft
* *merge* -> override draft changes into current live version
* *release-as-new* -> release draft as new page

### UI-States

##### Simple transitions

[plantuml, publisher-ui-states-without-alerts, svg]
....
state editLive : edit a live version
state PublisherExtension {
    state editDraft : edit a non live version
}

[*] -> editLive

[*] --> editDraft

editLive --> [*] : close
editDraft --> [*] : close

editDraft -> editDraft : save
editLive -> editDraft : save as draft

....

##### Save Live Modal

[plantuml, publisher-ui-alert-live, svg]
....
state editLive : edit a live version
state PublisherExtension {
    state editDraft : edit a non live version
    state askPublishLive : Ask if live version should really be published
}

[*] -> editLive

[*] --> editDraft

editLive --> [*] : close
editDraft --> [*] : close

editDraft -> editDraft : save
editLive -> editDraft : save as draft

editLive -> askPublishLive : save
askPublishLive -> editLive : publish
askPublishLive -> editDraft : draft

....

##### Publish Draft Modal*

[plantuml, publisher-ui-alert-publish-draft, svg]
....
state editLive : edit a live version
state PublisherExtension {
    state editDraft : edit a non live version
    state askPublishDraft : Ask if draft version should be published and merged
}

[*] -> editLive

[*] --> editDraft

editLive --> [*] : close
editDraft --> [*] : close

editDraft -> editDraft : save
editLive -> editDraft : save as draft

editDraft -> askPublishDraft : publish
askPublishDraft -> editLive : publish
askPublishDraft -> editDraft : abort
askPublishDraft -> editDraft : update outdated draft
askPublishDraft -> editDraft : new
....

[*] Only applicable if live version is connected to categories

##### Update Draft Modal

[plantuml, publisher-ui-alert-new-modal, svg]
....
state editLive : edit a live version
state PublisherExtension {
    state editDraft : edit a non live version
    state askUpdate : Ask if draft should be updated from live
}
[*] -> editLive

[*] --> editDraft

editLive --> [*] : close
editDraft --> [*] : close

editDraft -> editDraft : save
editLive -> editDraft : save as draft

editDraft -> askUpdate : update
askUpdate -> editDraft : skip
askUpdate -> editDraft : update from live
....
